"""Floor-plan analysis package."""

from .analyzer import (
    DEFAULT_MODEL,
    SCORE_CRITERIA,
    FloorPlanAnalysis,
    PIPELINE_CACHE_VERSION,
    analyze_cached_structure,
    analyze_floor_plan,
    build_analysis_prompt,
    build_extraction_prompt,
    compact_structure_for_scoring,
    deduplicate_topology_observations,
    load_knowledge,
    merge_verification_decisions,
    parse_structure_response,
    render_analysis_report,
    validate_connections,
    validate_scoring_json,
)
from .providers import (
    DEFAULT_OLLAMA_HOST,
    DEFAULT_OLLAMA_MODEL,
    FallbackClient,
    GeminiClient,
    OllamaClient,
    create_analysis_client,
)
from .cache import load_structure_cache, save_structure_cache, structure_cache_key

__all__ = [
    "DEFAULT_MODEL",
    "SCORE_CRITERIA",
    "FloorPlanAnalysis",
    "PIPELINE_CACHE_VERSION",
    "analyze_cached_structure",
    "analyze_floor_plan",
    "build_analysis_prompt",
    "build_extraction_prompt",
    "compact_structure_for_scoring",
    "deduplicate_topology_observations",
    "load_knowledge",
    "merge_verification_decisions",
    "parse_structure_response",
    "render_analysis_report",
    "validate_connections",
    "validate_scoring_json",
    "DEFAULT_OLLAMA_HOST",
    "DEFAULT_OLLAMA_MODEL",
    "FallbackClient",
    "GeminiClient",
    "OllamaClient",
    "create_analysis_client",
    "load_structure_cache",
    "save_structure_cache",
    "structure_cache_key",
]
